[package]
name = "hyperfs-storage"
description = "HyperFS Storage Server"
version = "0.1.0"
license = "MIT"
authors = ["Axel Etcheverry <axel@etcheverry.biz>"]

include = [
  "README.md",
  "Cargo.toml",
  "src/*.rs",
]

[dependencies]
clap        = "^2.24.1"
hyperfs-lib = { version = "^0.1", path = "../../lib" }

[features]
unstable = []
