language: go

sudo: required
dist: trusty

notifications:
  email: false

env:
  - GO111MODULE=on

go:
  - 1.11.x
  - master
  - tip

matrix:
  fast_finish: true
  allow_failures:
    - go: master
    - go: tip

cache: apt

install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.10.2
  - go get github.com/mattn/goveralls

script:
  - goveralls -v -race -covermode=atomic -service=travis-ci
  - golangci-lint run
