version: '3'

services:
  hyperfs-index:
    image: 127.0.0.1:5000/hyperfs-index
    environment:
        - PORT=8000
    ports:
      - "8000:8000"
      - "7946:7946"
    networks:
        - hyperfs-net
    deploy:
        replicas: 4
        placement:
            constraints: [node.role == manager]

networks:
    hyperfs-net:
