[package]
name = "hyperfs-api"
description = "HyperFS API Server"
version = "0.1.0"
license = "MIT"
authors = ["Axel Etcheverry <axel@etcheverry.biz>"]

include = [
  "README.md",
  "Cargo.toml",
  "src/*.rs",
]

[dependencies]
config        = "~0.4.1"
clap          = "~2.24.1"
iron          = "~0.5.1"
iron-cors     = "~0.5.1"
router        = "~0.5.1"
serde         = "~1.0.4"
serde_json    = "~1.0.2"
serde_derive  = "~1.0.4"
hyperfs-lib   = { version = "^0.1", path = "../../lib" }

[features]
unstable = []
